// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in player's profile: username, money, level, total profit, and cars sold.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("username, money, level, total_profit, total_cars_sold").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var get_leaderboard_default = defineTool2({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Return the top players ranked by total profit (public leaderboard).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: ctx.isAuthenticated() ? { headers: { Authorization: `Bearer ${ctx.getToken()}` } } : void 0,
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.rpc("get_leaderboard");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).slice(0, limit ?? 10);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { leaderboard: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wkdzupoobsrcqbeolmtb";
var mcp_default = defineMcp({
  name: "car-mechanic-tycoon-mcp",
  title: "Car Mechanic Tycoon",
  version: "0.1.0",
  instructions: "Tools for the Car Mechanic Tycoon Simulator. Use `get_my_profile` to read the signed-in player's stats, and `get_leaderboard` to read the public top players.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
